### ISSUE TITLE
error - add subdomain to existing domain

### ISSUE THREAD

**Issue by windsofchange** [promek/px-dns-da2cp#4]
`rndc: 'reload' failed: not found
rndc: 'reload' failed: not found`

**Comment by promek** [comment]
you will get this error if you do not have a domain.
because rndc works as below.

> rndc reload ${domain} IN internal;rndc reload ${domain} IN external;rndc flushname ${domain}

**Comment by maxigentr** [comment]
Hi @promek 
rndc gives error due to fast process.
If you correct line 65 as follows, the problem is corrected.

`    result=$( bash_run "sshpass -p \"${pass}\" ssh -oStrictHostKeyChecking=no -p ${port} root@${host} \"sleep 5; rndc reload ${domain} IN internal;rndc reload ${domain} IN external;rndc flushname ${domain}\"" )`
